### ISSUE TITLE
DarkTheme not matching DarkTheme

### ISSUE THREAD

**Issue by Hansaplast** [skalogryz/macosext#2]
Minor update to make this even better:

Seems that '**NSAppearanceNameVibrantDark**' does not match an actual DarkTheme.
To get the actual DarkTheme use '**NSAppearanceNameDarkAqua**' instead.

[Reference](https://developer.apple.com/documentation/appkit/nsappearancenamedarkaqua?language=objc)

**Comment by neurolabusc** [comment]
Curious, the theme `NSAppearanceNameDarkAqua` does not seem to exist on MacOS 10.13.6. Maybe the correct solution is to use DarkAqua if it exists (10.14 or later) and otherwise default to VibrantDark. I do not have 10.14 to test this, but I would think this would work:

```
procedure setThemeMode(Owner: TComponent; isDarkMode: boolean);
begin
  if (isDarkMode) then begin
     if not UpdateAppearance(Owner, macOSNSAppearanceNameDarkAqua) then
       UpdateAppearance(Owner, macOSNSAppearanceNameVibrantDark);
  end else
      UpdateAppearance(Owner, DefaultAppearance);
end;
```

**Comment by skalogryz** [comment]
NSAppearanceNameVibrantDark is the name used of dark theme for prior 10.14
NSAppearanceNameDarkAqua is available for since 10.14 only.

That's why Appearance name is set up by a string, rather than a predefined strict set.
You can always assign ANY name to the appearance.

**Comment by Hansaplast** [comment]
Interesting, I did not know that! Thanks Dmitry!
Does 10.13.x cause problems when assigning it NSAppearanceNameDarkAqua, or does it just ignore it?

**Comment by neurolabusc** [comment]
Dmitry's function "UpdateAppearance" returns false when attempting to assign NSAppearanceNameDarkAqua on 10.13.6 (and the theme does not change, remaining light). Therefore, the conditional I suggest above implements NSAppearanceNameDarkAqua if possible but falls back to macOSNSAppearanceNameVibrantDark (and if that fails, no dark mode is available).
